export const data = {
  nodes: [
    { name: "Samuel G Rodriques", group: 1, affiliation: "Director and CEO Future House, Inc", id: "1", email: "sam.rodriques@gmail.com", description: "I am an inventor and entrepreneur. I have invented a new nanofabrication method, a new approach to sensing neural activity with probes in the bloodstream, new ways to extract spatial and temporal information from RNA sequencing, a new protein sequencing method, and a new approach to mapping connections in the brain, among other things. I founded the Applied Biotechnology Laboratory at the Francis Crick Institute in January 2021 with the goal of combining bioengineering and entrepreneurship to develop and deploy new biotechnologies that address major unmet needs for biology and medicine. In 2023, I launched Future House, a new research moonshot in San Francisco, focused on building an AI Scientist." },
    { name: "Samuel G Rodriques", group: 1, affiliation: "Director and CEO Future House, Inc", id: "1", email: "sam.rodriques@gmail.com", description: "私は発明家で起業家です。私は新しいナノファブリケーション手法、血流中のプローブを使用した神経活動の検知に対する新しいアプローチ、RNAシーケンシングからの空間と時間の情報を抽出する新しい方法、新しいタンパク質シーケンシング手法、および脳の結合をマッピングする新しいアプローチなど、さまざまなものを発明しました。私は、フランシス・クリック研究所において、バイオエンジニアリングと起業精神を組み合わせて、生物学と医学の重要な未解決のニーズに対処する新しいバイオテクノロジーを開発し、展開することを目指すApplied Biotechnology Laboratoryを2021年1月に設立しました。また、2023年には、サンフランシスコでの新しいリサーチムーンショットであるFuture Houseを立ち上げ、AI Scientistの構築に焦点を当てました。" },
    { name: "Adam H Marblestone", group: 1, affiliation: "CEO of Convergent Research", id: "2", email: "adam.h.marblestone@gmail", description: "General automation, and science: Generative AI is moving fast, with scaling laws visibly playing out. What will the next few years of deep learning bring us, in terms of real world impact outside of tech/software? I’ve been hearing some bold predictions for disruption. I think about this a lot, since my job is to help the world do beneficial, counterfactually necessary, science projects. If LLMs will just up and replace or transform large swaths of scientific research anytime soon, I need to be aware." },
    { name: "Tom Kalil", group: 2, affiliation: "Chief Innovation Officer at Schmidt Futures", id: "3", email: "aaa", description: "Prior to Schmidt Futures, Tom served in the White House for two Presidents (Obama and Clinton), helping to design and launch national science and technology initiatives in areas such as nanotechnology, the BRAIN initiative, data science, materials by design, robotics, commercial space, high-speed networks, access to capital for startups, high-skill immigration, STEM education, learning technology, startup ecosystems, and the federal use of incentive prizes." },
    { name: "Donald W Braben", group: 1, affiliation: "", id: "4", email: "aaa", description: "I am a scientist and author currently striving to protect freedom for potentially great scientists from the rising tides of mindless bureaucracy." },
    { name: "Brian Nosek", group: 1, affiliation: "Co-founder and Executive Director of Center for Open Science", id: "aaa", email: "5", description: "Brian Nosek’s research and applied interests are to understand how people and systems produce values-misaligned behavior; to develop, implement, and evaluate solutions to align behavior with values; and, to improve research methods and culture to accelerate progress in science. I spend a lot of time thinking about how to improve the scientific method. For example, I believe that replication is important for developing and improving scientific theories, and that precommitment is important for reducing unwanted bias. My theoretical and empirical research on improving methodology has shaped the initiatives offered through the Center for Open Science." },
    { name: "Michael Nielsen", group: 1, affiliation: "", id: "aaa", email: "6", description: "ppp" },
    { name: "Kanjun Qiu", group: 1, affiliation: "", id: "aaa", email: "7", description: "ppp" },
  ],
  links: [
  ]
}